import localFont from 'next/font/local';
import "./globals.css";


const sportingGrotesque = localFont({
  src: [
    {
      path: './assets/fonts/SportingGrotesque-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './assets/fonts/SportingGrotesque-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-sporting',
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`font-sporting ${sportingGrotesque.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
